export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const PRIMARY_NAV_AUTH = 'PRIMARY_NAV_AUTH';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_DELIVERY_MODE = 'SET_DELIVERY_MODE';
